### ISSUE TITLE
License modification

### ISSUE THREAD

**Issue by bvernoux** [mbasaglia/Qt-History-LineEdit#1]
In https://github.com/mbasaglia/Qt-History-LineEdit/blob/master/COPYING you have:
- GNU LESSER GENERAL PUBLIC LICENSE Version 3, 29 June 2007

In code:
- https://github.com/mbasaglia/Qt-History-LineEdit/blob/master/src/history_line_edit.cpp & 
- https://github.com/mbasaglia/Qt-History-LineEdit/blob/master/src/history_line_edit.hpp
- It is GNU General Public License version 3 or more

Could you fix the license for the source code as it shall be LGPL v3 instead of GPL v3  ?

The best for such simple and useful code (in order to be re-used in commercial software without conflict with GPL/LGPL ...) will be to release it to a fully open license like [MIT license](https://en.wikipedia.org/wiki/MIT_License) or even [Apache v2.0](http://opensource.org/licenses/Apache-2.0), it will be really a must

**Comment by mbasaglia** [comment]
Yeah sorry, I use templates to generate license boilerplates and sometimes I mix them up.
The top level COPYING/Readme have the right license, I'll fix the sources ASAP.

I'm not a fan of licenses lacking copyleft as I want my code to remain free for all.

**Comment by bvernoux** [comment]
Thanks for the feedback and fix/clarifications for the LGPL license, like that the plugin can be used in commercial product ...
Just for information there is some little typo in some header which say "COLOR_WHEEL_PLUGIN ..." instead of "History Line Edit Plugin"

**Comment by mbasaglia** [comment]
I've updated the code with the proper licensing.
